# whether to display messages in the system log about queue activity
verbose: true

global:
  # global server login limit. Set less than your server.properties to have room for
  # reserved logins. You must always have at least 1 spot open in order for people
  # to be able to queue; if the server is totally full, MineCraft/Bukkit won't let
  # players connect at all, so this plugin cannot detect them.
  limit: 20

  # any groups listed here can login even if server is at the global Limit
  limitExemptPerms:
    - group.Moderator

  # the time, in seconds, that someone must attempt to login in order to hold
  # their place in the queue.
  queueLoginTime: 120

  # the max time, in seconds, someone is allowed to be in the queue before their
  # place in the queue is erased and they start over. You can set this to 0 to
  # not use this setting, in which case the only setting that matters is the
  # queueLoginTime above.
  queueMaxTime: 600

  # how many seconds a player has to reconnect after disconnecting (their
  # spot on the server is reserved for only this long)
  reconnectTime: 60

  # if defined, higher ranks skip lower ranks in the queue
#  queueRankPerms:
#    "100": group.Guest
#    "200": group.Member
#    "300": group.PaidMember
#    "400": group.Moderator
#    "1000": group.Admin

  # if defined, the highest value is used for the matching permission. If
  # no matching permission is found, the default value set in
  # "queueLoginTime" above is used
#  queueLoginTimeByPerm:
#    group.Guest: 60
#    group.Member: 120

# define any per-group limits
groupLimits:
  # this name is irrelevant, just has to be unique. "entry1", "entry2", "foo3".. whatever
  entry1:
    # permissions listed here apply to this entry
    permissions:
      - group.GuestLimit
      - group.NewbieLimit

    # the limit for the groups in this entry
    limit: 5

    # the limit doesn't apply until server is at least at this user load. Comment
    # out or set to -1 to have limit apply no matter what current server pop is.
    ifOver: 10

    # this can be used to require someone else be online in order for people in
    # this entry to login. For example you can require that a mod be online in
    # order for Guests to login.
    requiredOnlinePerms:
      - group.Moderator
      - group.Admin

    # If this is true, the requireOnlinePerms only applies to new logins. Anyone
    # who has logged in at least once before will be exempt from the
    # requiredOnlinePerms check.
    requiredPermsOnlyForNew: true

messages:
  limitReached: "The number of reserved slots for your rank has been reached. Try again later"
  noPermsOnlineString: "The required rank is not online at this time"
