name: ${project.name}
main: org.morganm.loginlimiter.LoginLimiter
url: ${project.url}
version: ${project.version}
author: morganm
commands:
  ll:
    description: Admin control functions for LoginLimiter
    permission: loginlimiter.admin
    usage: /<command> reload - reload the config file
  offduty:
    description: Go off duty, no longer counted for required login perm
    permission: loginlimiter.duty
  onduty:
    description: Go on duty
    permission: loginlimiter.duty
  dutylist:
    description: List everyone who is OFF duty
    permission: loginlimiter.duty
